cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_summary, name='cart_summary'),
    path('add/', views.cart_add, name='cart_add'),
    path('delete/', views.cart_delete, name='cart_delete'),
    path('update/', views.cart_update, name='cart_update'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('cart/', include('cart.urls', namespace='cart')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.all_products, name='all products'),
    path('books/<slug:slug>', views.product_detail, name='product_detail'),
    path('/searchbar', views.searchbar, name='searchbar'),
]

cart/models.py
from django.db import models

# Create your models here.

store/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
    
class Book(models.Model):
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, default='Unknown')
    user_rating = models.DecimalField(max_digits=4, decimal_places=1)
    price = models.DecimalField(max_digits=4, decimal_places=0)
    year = models.DecimalField(max_digits=4, decimal_places=0)
    genre = models.CharField(max_length=30)
    slug = models.SlugField(max_length=255)
    image = models.ImageField(upload_to='images/', default= 'images/default.jpg')

    class Meta:
        verbose_name_plural = 'Books'
        ordering = ('-user_rating',)

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug])

    def _str_(self):
        return self.title

cart/views.py
from django.http.response import JsonResponse
from django.shortcuts import get_object_or_404, render
from django.http import JsonResponse

from .cart import Cart
from store.models import Book
# Create your views here.

def cart_summary(request):
    cart = Cart(request)
    return render(request, 'store/cart/cart.html', {'cart': cart})

def cart_add(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        book_id = int(request.POST.get('bookid'))
        book_qty = int(request.POST.get('bookqty'))
        book = get_object_or_404(Book, id=book_id)
        cart.add(book=book, qty=book_qty)
        cartqty = cart.__len__()
        response = JsonResponse({'qty': cartqty})
        return response

def cart_delete(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        book_id = int(request.POST.get('bookid'))
        cart.delete(book=book_id)

        cartqty = cart.__len__()
        carttotal = cart.get_total_price()
        response = JsonResponse({'qty': cartqty, 'subtotal': carttotal})
        return response

def cart_update(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        book_id = int(request.POST.get('bookid'))
        book_qty = int(request.POST.get('bookqty'))
        cart.update(book=book_id, qty=book_qty)

        cartqty = cart.__len__()
        carttotal = cart.get_total_price()
        response = JsonResponse({'qty': cartqty, 'subtotal': carttotal})
        return response

store/views.py
from django.shortcuts import render, get_object_or_404

from .models import Book

def all_products(request):
    books = Book.objects.all()
    return render(request, 'store/home.html', {'books': books})

def product_detail(request, slug):
    book = get_object_or_404(Book, slug=slug)
    return render(request, 'store/books/detail.html', {'book': book})

def searchbar(request):
    if request.method == 'GET':
        search = request.GET.get('search')
        books = Book.objects.filter(title__contains=search)
        return render(request, 'store/searchbar.html', {'books': books})

templates/store/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>{% block title %}paperback{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous">
    </script>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-light bg-white border-bottom">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">paperback</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item active">
                            <a class="nav-link" aria-current="page" href="/">Home</a>
                        </li>
                    </ul>
                    <a type="button" role="button" href="{% url "cart:cart_summary" %}"
                        class="btn btn-outline-secondary">
                        {% with total_qty=cart|length %}
                            <div id= "cart-qty" class="d-inline-flex">
                            {% if total_qty > 0 %}
                                {{ total_qty }}
                            {% else %}
                                0
                            {% endif %}
                            </div>
                        {% endwith %}
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                            class="bi bi-cart" viewBox="0 0 16 16">
                            <path
                                d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                        </svg>
                        Cart
                    </a>
                </div>
        </nav>
    </header>
    <div id="content">{% block content %} {% endblock %}</div>
</body>

</html>

templates/store/books/detail.html
{% extends "store/base.html" %}
{% load static %}
{% block title %}
{{ book.name }}
{% endblock %}
{% block content %}
<div class="container">
    <main class="pt-5">
        <div class="row g-3">
            <div class="col-md-5 col-lg-5 order-md-first bg-light">
                <img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image" src="{{ book.image.url }}">
            </div>
            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                <h1 class="mb-0 h4">{{ book.title }}</h1>
                <p><span class="lead">{{ book.author }}</span> (Author)</p>
                <div class="border">
                    <div class="col border-bottom">
                        <div class="row p-3">
                            <div class="col-6">Hardback</div>
                            <div class="col-6 text-end"><span class="h4 fw-bold">${{ book.price }}</span></div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row p-3">
                            <div class="col-6">
                                <label for="select">Qty</label>
                                <select id="select">
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                </select>

                            </div>
                            <div align="right"><button type="button" id="add-button" value="{{book.id}}" class="btn btn-secondary btn-sm">Add to cart</button></div></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

</div>

<script>
    $(document).on('click', '#add-button', function (e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "cart:cart_add" %}',
            data: {
                bookid: $('#add-button').val(),
                bookqty: $('#select option:selected').text(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post',
            },
            success: function (json) {
                document.getElementById("cart-qty").innerHTML = json.qty
            },
            error: function (xhr, errmsg, err) {}
        });
    })
</script>

{% endblock %}

templates/store/cart/cart.html
{% extends "../base.html" %}
{% load static %}
{% block title %}Cart Summary{% endblock %}
{% block content %}

<main class="pt-5">
  <div class="container">
    <h1 class="h5">Shopping cart</h1>
    {% for item in cart %}
    {% with book=item.book %}
    <div data-index="{{book.id}}" class="row mb-4 border product-item">
      <div class="col-md-3 col-lg-2 order-md-first bg-light">
        <img class="img-fluid mx-auto d-block" width="120px" alt="Responsive image" src="{{ book.image.url }}">
      </div>
      <div class="col-md-9 col-lg-10 ps-md-3 ps-lg-10">
        <a href="{{ book.get_absolute_url }}" class="text-decoration-none text-reset">
          <h1 class="h5 pt-2">{{ book.title }}</h1>
        </a>
        <div class="border">
          <div class="col border-bottom">
            <div class="row p-3">
              <div class="col-6">{{ book.title }}</div>
              <div class="col-6 text-end"><span class="h6 fw-bold">${{ book.price }}</span></div>
            </div>
          </div>
          <div class="col">
            <div class="row p-3">
              <div class="col-12">
                <label for="select">Qty</label>
                <select id="select{{book.id}}">
                  <option selected>
                    {{item.qty}}
                  </option>
                  <option value="">1</option>
                  <option value="">2</option>
                  <option value="">3</option>
                  <option value="">4</option>
                </select>
                <button type="button" id="update-button" data-index="{{book.id}}"
                  class="btn btn-outline-secondary btn-sm update-button">
                  Update
                </button>
                <button type="button" id="delete-button" data-index="{{book.id}}"
                  class="btn btn-outline-secondary btn-sm delete-button">
                  Delete
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endwith %}
    {% endfor %}
    <div class="col-12 text-end">
      <div class="h6 fw-bold">Sub Total: $<div id="subtotal" class="d-inline-flex">{{cart.get_total_price}}</div></div>
    </div>
  </div>
</main>

<script>
  // Delete Item
  $(document).on('click', '.delete-button', function (e) {
    e.preventDefault();
    var prodid = $(this).data('index');
    $.ajax({
      type: 'POST',
      url: '{% url "cart:cart_delete" %}',
      data: {
        bookid: $(this).data('index'),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: 'post'
      },
      success: function (json) {
        $('.book-item[data-index="' + prodid + '"]').remove();
        document.getElementById("subtotal").innerHTML = json.subtotal;
        document.getElementById("cart-qty").innerHTML = json.qty
      },
      error: function (xhr, errmsg, err) {}
    });
  })

  // Update Item
  
  $(document).on('click', '.update-button', function (e) {
    e.preventDefault();
    var prodid = $(this).data('index');
    $.ajax({
      type: 'POST',
      url: '{% url "cart:cart_update" %}',
      data: {
        bookid: $(this).data('index'),
        bookqty: $('#select' + prodid + ' option:selected').text(),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: 'post'
      },
      success: function (json) {
        document.getElementById("cart-qty").innerHTML = json.qty
        document.getElementById("subtotal").innerHTML = json.subtotal
      },
      error: function (xhr, errmsg, err) {}
    });
  })
</script>

{% endblock %}

templates/store/home.html
{% extends "./base.html" %}
{% load static %}
{% block title %}Home{% endblock %}
{% block content %}

<main>

  <div class="bg-dark text-secondary px-4 py-5 text-center">
    <div class="py-5">
      <h1 class="display-5 fw-bold text-white">paperback.</h1>
      <div class="col-lg-6 mx-auto">
        <p class="fs-5 mb-4">leading in getting you the books you love, fast.</p>
        <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
          <form action="{% url 'store:searchbar' %}" method="get">
            <input type="text" name="search" />
            <button type="submit">Search</button>
          </form>
        </div>
      </div>
    </div>
  </div>


  <div class="album py-5 bg-light">
    <div class="container">

      <div class="pb-3 h5">All Books</div>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

        {% for book in books %}
        <div class="col">
          <div class="card shadow-sm">
            <img class="img-fluid" alt="Responsive image" src="{{ book.image.url }}">
            <div class="card-body">
              <p class="card-text">
                <a class="text-dark text-decoration-none" href="{{ book.get_absolute_url }}">{{ book.title }}</a>
                <div align="right" class="pb-1 h5">${{ book.price }}</div>
              </p>
              <div class="d-flex justify-content-between align-items-center">
              </div>
            </div>
          </div>
        </div>

        {% endfor %}

      </div>
    </div>
  </div>


</main>

{% endblock %}

templates/store/searchbar.html
{% extends "./base.html" %}
{% load static %}
{% block title %}Home{% endblock %}
{% block content %}


<main>
    <div class="bg-dark text-secondary px-4 py-5 text-center">
        <div class="py-5">
            <h1 class="display-5 fw-bold text-white">paperback.</h1>
            <div class="col-lg-6 mx-auto">
                <p class="fs-5 mb-4">leading in getting you the books you love, fast.</p>
                <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
                    <form action="{% url 'store:searchbar' %}" method="get">
                        <input type="text" name="search" />
                        <button type="submit">Search</button>
                    </form>
                </div>
            </div>
        </div>
    </div>


    <div class="album py-5 bg-light">
        <div class="container">
            {% if books %}
            <div class="pb-3 h5">Search Results</div>
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
                {% for book in books %}
                <div class="col">
                    <div class="card shadow-sm">
                        <img class="img-fluid" alt="Responsive image" src="{{ book.image.url }}">
                        <div class="card-body">
                            <p class="card-text">
                                <a class="text-dark text-decoration-none"
                                    href="{{ book.get_absolute_url }}">{{ book.title }}</a>
                                <div align="right" class="pb-1 h5">${{ book.price }}</div>
                            </p>
                            <div class="d-flex justify-content-between align-items-center">
                            </div>
                        </div>
                    </div>
                </div>

                {% endfor %}
                {% else %}
                <div class="pb-3 h5">Nothing Found</div>
                {% endif %}
            </div>
        </div>
    </div>


</main>



{% endblock %}